### ISSUE TITLE
Detected by Windows Defender ??

### ISSUE THREAD

**Issue by cymilad** [r3nhat/GRAT2#1]
Detected by Windows Defender And Is there a way around it?

![problem](https://user-images.githubusercontent.com/22496001/94986506-40ff1d80-056c-11eb-8ac8-aab9b0b1281c.PNG)

**Comment by r3nhat** [comment]
Hello,

Thanks for your message.

Unfortunately, bypassing AV engines are out of scope for this project.

Thanks again.
